development: &dev
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: <%= ENV['DB_ENV_MYSQL_POOL'] || 25 %>
  database: <%= ENV['DB_ENV_MYSQL_DB'] || 'ccc360' %>
  username: <%= ENV.fetch('DB_ENV_MYSQL_USER') %>
  password: <%= ENV['DB_ENV_MYSQL_PASS'] %>
  host: <%= ENV['DB_PORT_3306_TCP_ADDR'] %>

production:
  <<: *dev

uscm:
  <<: *dev
  database: <%= ENV['DB_ENV_MYSQL_DB_USCM'] %>

staging:
  <<: *dev

test:
  <<: *dev
  database: <%= ENV['DB_ENV_MYSQL_DB_TEST'] || 'ccc360_test' %>
  pool: <%= ENV['DB_ENV_MYSQL_POOL_TEST'] || 25 %>
  username: <%= ENV['DB_ENV_MYSQL_USER_TEST'] || ENV['DB_ENV_MYSQL_USER'] %>
  password: <%= ENV['DB_ENV_MYSQL_PASS_TEST'] || ENV['DB_ENV_MYSQL_PASS'] %>
  host: <%= ENV['DB_PORT_3306_TCP_ADDR_TEST'] || ENV['DB_PORT_3306_TCP_ADDR'] %>
