development:
  adapter: postgresql
  encoding: unicode
  database: mpd_development
  pool: 5
  username: luke
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mpd_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: mpd_production
  pool: 5
  username: postgres
  password:

#development:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: mpd_development
#  pool: 5
#  username: root
#  password:
#  socket: /var/run/mysqld/mysqld.sock

#test:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: mpd_test
#  pool: 5
#  username: root
#  password:
#  socket: /var/run/mysqld/mysqld.sock

#production:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: mpd_production
#  pool: 5
#  username: root
#  password:
#  socket: /var/run/mysqld/mysqld.sock
